name: Deploy

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.OWNER_EMAIL}}

      - name: Clone CodeInside Backend Repository
        run: |
          git clone https://github.com/MagisterFelix/CodeInside
          echo ${{secrets.SETTINGS_FILE}} > CodeInside/core/settings.py
      - name: Make DockerFile
        run: |
          cd CodeInside
          echo "
          # pull official base image
          FROM python:3.10-alpine

          # set work directory
          WORKDIR /app

          # set environment variables
          ENV PYTHONDONTWRITEBYTECODE 1
          ENV PYTHONUNBUFFERED 1
          ENV DEBUG 1
          ENV SECRET_KEY $secrets.DJANGO_SECRET_KEY

          # install psycopg2
          RUN apk update \
              && apk add --virtual build-deps gcc python3-dev musl-dev \
              && apk add postgresql-dev \
              && pip install psycopg2 \
              && apk del build-deps \
              && apk add gcc \
              && apk add libc-dev \
              && apk add linux-headers \
              && apk add g++


          # install dependencies
          COPY ./requirements.txt .
          RUN pip install -r requirements.txt

          # copy project
          COPY . .

          # collect static files
          RUN python manage.py collectstatic --noinput

          # add and run as non-root user
          RUN adduser -D myuser
          USER myuser

          # run gunicorn
          CMD gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
          " > Dockerfile
          echo "
          __pycache__
          *.pyc
          venv/
          db.sqlite3" > .dockerignore
          
      - name: Build Docker 
        run: |
          cd CodeInside
          heroku config:set SECRET_KEY="53175bcc0524f37b47062fafdda28e3f8eb91d519ca0a184ca71bbebe72f969a" -a ${{secrets.HEROKU_APP_NAME}}
          docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web .
          docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
          heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web
          heroku run python manage.py makemigrations -a ${{secrets.HEROKU_APP_NAME}}
          heroku run python manage.py migrate -a ${{secrets.HEROKU_APP_NAME}}
          heroku run DJANGO_SUPERUSER_USERNAME=root \
          DJANGO_SUPERUSER_PASSWORD=root \
          DJANGO_SUPERUSER_EMAIL=root@root.root \
          python manage.py createsuperuser --noinput


