name: Deploy

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.OWNER_EMAIL}}

      - name: Clone CodeInside Backend Repository
        run: |
          git clone https://github.com/MagisterFelix/CodeInside
          echo ${{secrets.SETTINGS_FILE}} > CodeInside/core/settings.py

