name: Deploy

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      HEROKU_AUTH: ${{ secrets.HEROKU_AUTH }}
    steps:
      - uses: actions/checkout@v2

      - name: Clone CodeInside Backend Repository
        run: |
          git clone https://github.com/AlexeyTrofimenko/laughing-siesta
      - name: Make DockerFile
        run: |
          cd laughing-siesta
          echo "
          # pull official base image
          FROM python:3.10-alpine

          # set work directory
          WORKDIR /app

          # set environment variables
          ENV PYTHONDONTWRITEBYTECODE 1
          ENV PYTHONUNBUFFERED 1
          ENV DEBUG 1
          ENV SECRET_KEY $secrets.DJANGO_SECRET_KEY

          # install psycopg2
          RUN apk update \
              && apk add --virtual build-deps gcc python3-dev musl-dev \
              && apk add postgresql-dev \
              && pip install psycopg2 \
              && apk del build-deps \
              && apk add gcc \
              && apk add libc-dev \
              && apk add linux-headers \
              && apk add g++


          # install dependencies
          COPY ./requirements.txt .
          RUN pip install -r requirements.txt

          # copy project
          COPY . .

          # collect static files
          RUN python manage.py collectstatic --noinput

          # add and run as non-root user
          RUN adduser -D myuser
          USER myuser

          # run gunicorn
          CMD gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
          " > Dockerfile
          echo "
          __pycache__
          *.pyc
          venv/
          db.sqlite3" > .dockerignore
      - name: Install Heroku CLI
        run: |
          cd laughing-siesta
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          echo "machine api.heroku.com
                  login oleksii.trofimenko@nure.ua
                  password $secrets.HEROKU_AUTH
                machine git.heroku.com
                  login oleksii.trofimenko@nure.ua
                  password $secrets.HEROKU_AUTH > ~/.netrc
          heroku container:login
#      - name: Build Docker
#        run: |
#          cd laughing-siesta
#          docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web .
#      - name: Push Docker
#        run: |
#          cd laughing-siesta
#          docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
#      - name: Release Docker
#        run: |
#          cd laughing-siesta
#          heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web
